---
- name: Make facts.d directory
  file:
    path: /etc/ansible/facts.d/
    state: directory

- name: Create AWX facts.d files
  shell: echo \"$(tr -dc '[:alnum:]' < /dev/urandom | head -c 40)\" > /etc/ansible/facts.d/pangeo_secret_token.fact
  args:
    creates: /etc/ansible/facts.d/pangeo_secret_token.fact
  register: state

- name: Make facts.d files accessible by root only
  file:
    path: /etc/ansible/facts.d/pangeo_secret_token.fact
    mode: "u=rw,g=,o="

- name: Reload facts
  setup:
  when: state is changed
...
